### ISSUE TITLE
assign to reviewer based on "review by @mention"

### ISSUE THREAD

**Issue by adriaanm** [scala/scabot#16]

**Comment by SethTisue** [comment]
when Adriaan made this ticket, "assign to reviewer" would have used the "Assignees" feature, but now it would be more appropriate to use GitHub's new(-ish) code review features

you might hope that feature would obviate the need for this entirely, but, at least for now you need write access to the repo to request a reviewer, as per https://github.com/scala/scala-dev/issues/289. sigh

**Comment by SethTisue** [comment]
fixed by #68, thank you @teldosas !
