### ISSUE TITLE
Scabot stopped assigning milestones to PRs

### ISSUE THREAD

**Issue by SethTisue** [scala/scabot#51]
the problem started 3 days ago. noticed by @retronym

(I have since gone and manually assigned milestones to all recent PRs. that will need to be done again once a fix is in.)

**Comment by SethTisue** [comment]
temporarily fixed by making sure all open milestones in the scala/scala repo had non-empty descriptions. the GitHub API was returning `null` instead of `""`, causing JSON unmarshalling to blow up

I'll submit a separate PR with a more permanent fix.

**Comment by adriaanm** [comment]
:cake: !
