### ISSUE TITLE
upgrade to Scala 2.12.0

### ISSUE THREAD

**Issue by SethTisue** [scala/scabot#64]
this will also involve using newer Akka & Play versions

we can't do this until Play publishes for 2.12, though

**Comment by SethTisue** [comment]
Spray probably won't be published for 2.12 (reference: https://github.com/spray/spray/issues/1132), so we'll need to switch libraries — akka-http seems like the obvious choice for a replacement.

**Comment by SethTisue** [comment]
Play is on 2.12, but only for Play 2.6; we're on Play 2.4.

**Comment by SethTisue** [comment]
there aren't Play artifacts yet for 2.12, just a development branch

**Comment by adriaanm** [comment]
Play 2.6-m1 should be out in a few weeks. Porting to akka http won't be trivial, but a good investment

**Comment by SethTisue** [comment]
pretty tempting to just stay on 2.11, actually...

**Comment by SethTisue** [comment]
At this point it seems likelier that we would get rid of Scabot altogether.

**Comment by SethTisue** [comment]
there's also #96, which remains open — if we ever moved to new Scala, I think it would be because we wanted to get on newer Play (or akka-http)
